packages:
  - packages/*
  - packages/*/
  - packages/*/*

  - services/*
  - services/*/*
  - services/*/*/*
  - apps/*

  - "!infra"
  - "!imgs"
  - "!.github"
  - "!.idea"
  - "!.vscode"

onlyBuiltDependencies:
  - sharp

useNodeVersion: 20.19.0
