import { Report } from '../entities/report.entity';
import { ExportResult } from './export.types';

export class HtmlExporter {
  export(report: Report, includeMetadata: boolean = true): ExportResult {
    const html = this.generateHtml(report, includeMetadata);
    const buffer = Buffer.from(html, 'utf-8');
    const filename = this.sanitizeFilename(report.name) + '.html';

    return {
      buffer,
      filename,
      mimeType: 'text/html',
    };
  }

  private generateHtml(report: Report, includeMetadata: boolean): string {
    const contentHtml = this.markdownToHtml(report.content || '');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(report.name)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 { color: #1a1a1a; border-bottom: 2px solid #eee; padding-bottom: 10px; }
    h2 { color: #2a2a2a; margin-top: 30px; }
    h3 { color: #3a3a3a; }
    .metadata {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 20px;
      margin: 20px 0;
    }
    .metadata table { width: 100%; border-collapse: collapse; }
    .metadata td { padding: 8px 0; }
    .metadata td:first-child { font-weight: 600; width: 150px; color: #666; }
    .content {
      background: #fff;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      padding: 30px;
      margin: 20px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      font-size: 0.9em;
      color: #888;
      text-align: center;
    }
    pre {
      background: #f4f4f4;
      padding: 15px;
      border-radius: 4px;
      overflow-x: auto;
    }
    code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 0.9em;
    }
    blockquote {
      border-left: 4px solid #ddd;
      margin: 0;
      padding-left: 20px;
      color: #666;
    }
    ul, ol { padding-left: 25px; }
    li { margin: 5px 0; }
  </style>
</head>
<body>
  <h1>${this.escapeHtml(report.name)}</h1>

  ${includeMetadata ? this.generateMetadataSection(report) : ''}

  ${report.description ? `
  <h2>Description</h2>
  <p>${this.escapeHtml(report.description)}</p>
  ` : ''}

  <div class="content">
    ${contentHtml}
  </div>

  ${includeMetadata && report.tokenUsage ? this.generateTokenUsageSection(report.tokenUsage) : ''}

  <div class="footer">
    <p>Generated by AI Report System</p>
  </div>
</body>
</html>`;
  }

  private generateMetadataSection(report: Report): string {
    return `
  <div class="metadata">
    <h2>Report Information</h2>
    <table>
      <tr><td>Type</td><td>${report.type}</td></tr>
      <tr><td>Status</td><td>${report.status}</td></tr>
      <tr><td>Created</td><td>${new Date(report.createdAt).toLocaleString()}</td></tr>
      ${report.completedAt ? `<tr><td>Completed</td><td>${new Date(report.completedAt).toLocaleString()}</td></tr>` : ''}
      ${report.llmProvider ? `<tr><td>LLM Provider</td><td>${report.llmProvider}</td></tr>` : ''}
      ${report.llmModel ? `<tr><td>Model</td><td>${report.llmModel}</td></tr>` : ''}
    </table>
  </div>`;
  }

  private generateTokenUsageSection(tokenUsage: Record<string, any>): string {
    const rows = Object.entries(tokenUsage)
      .map(([key, value]) => `<tr><td>${key}</td><td>${value}</td></tr>`)
      .join('');

    return `
  <div class="metadata">
    <h2>Token Usage</h2>
    <table>${rows}</table>
  </div>`;
  }

  private markdownToHtml(markdown: string): string {
    if (!markdown) return '<p><em>No content generated</em></p>';

    let html = this.escapeHtml(markdown);

    // Headers
    html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');

    // Bold and italic
    html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    // Code blocks
    html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

    // Lists
    html = html.replace(/^\- (.*$)/gm, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');

    // Numbered lists
    html = html.replace(/^\d+\. (.*$)/gm, '<li>$1</li>');

    // Blockquotes
    html = html.replace(/^> (.*$)/gm, '<blockquote>$1</blockquote>');

    // Horizontal rules
    html = html.replace(/^---$/gm, '<hr>');

    // Paragraphs
    html = html.replace(/\n\n/g, '</p><p>');
    html = '<p>' + html + '</p>';

    // Clean up empty paragraphs
    html = html.replace(/<p><\/p>/g, '');
    html = html.replace(/<p>(<h[1-6]>)/g, '$1');
    html = html.replace(/(<\/h[1-6]>)<\/p>/g, '$1');
    html = html.replace(/<p>(<ul>)/g, '$1');
    html = html.replace(/(<\/ul>)<\/p>/g, '$1');
    html = html.replace(/<p>(<hr>)<\/p>/g, '$1');
    html = html.replace(/<p>(<pre>)/g, '$1');
    html = html.replace(/(<\/pre>)<\/p>/g, '$1');

    return html;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50);
  }
}
