import { Report } from '../entities/report.entity';
import { ExportResult } from './export.types';

export class MarkdownExporter {
  export(report: Report, includeMetadata: boolean = true): ExportResult {
    const lines: string[] = [];

    // Title
    lines.push(`# ${report.name}`);
    lines.push('');

    // Metadata section
    if (includeMetadata) {
      lines.push('## Report Information');
      lines.push('');
      lines.push(`- **Type:** ${report.type}`);
      lines.push(`- **Status:** ${report.status}`);
      lines.push(`- **Created:** ${new Date(report.createdAt).toLocaleString()}`);
      if (report.completedAt) {
        lines.push(`- **Completed:** ${new Date(report.completedAt).toLocaleString()}`);
      }
      if (report.llmProvider) {
        lines.push(`- **LLM Provider:** ${report.llmProvider}`);
      }
      if (report.llmModel) {
        lines.push(`- **Model:** ${report.llmModel}`);
      }
      lines.push('');
    }

    // Description
    if (report.description) {
      lines.push('## Description');
      lines.push('');
      lines.push(report.description);
      lines.push('');
    }

    // Main content
    lines.push('## Content');
    lines.push('');
    lines.push(report.content || '*No content generated*');
    lines.push('');

    // Token usage
    if (includeMetadata && report.tokenUsage) {
      lines.push('---');
      lines.push('');
      lines.push('## Token Usage');
      lines.push('');
      for (const [key, value] of Object.entries(report.tokenUsage)) {
        lines.push(`- **${key}:** ${value}`);
      }
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push(`*Generated by AI Report System*`);

    const content = lines.join('\n');
    const buffer = Buffer.from(content, 'utf-8');
    const filename = this.sanitizeFilename(report.name) + '.md';

    return {
      buffer,
      filename,
      mimeType: 'text/markdown',
    };
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50);
  }
}
