import { Report } from '../entities/report.entity';
import { ExportResult } from './export.types';
import { HtmlExporter } from './html-exporter';

/**
 * PDF Exporter using HTML-to-PDF conversion.
 * In production, integrate with puppeteer or pdfkit for better PDF generation.
 * For now, we generate HTML with print-friendly styles that can be converted to PDF.
 */
export class PdfExporter {
  private htmlExporter: HtmlExporter;

  constructor() {
    this.htmlExporter = new HtmlExporter();
  }

  async export(report: Report, includeMetadata: boolean = true): Promise<ExportResult> {
    // Generate print-optimized HTML
    const html = this.generatePrintHtml(report, includeMetadata);
    const buffer = Buffer.from(html, 'utf-8');
    const filename = this.sanitizeFilename(report.name) + '.html';

    // Note: In production, use puppeteer to convert HTML to PDF:
    // const browser = await puppeteer.launch();
    // const page = await browser.newPage();
    // await page.setContent(html);
    // const pdfBuffer = await page.pdf({ format: 'A4' });
    // await browser.close();

    return {
      buffer,
      filename,
      mimeType: 'text/html', // Change to 'application/pdf' when using puppeteer
    };
  }

  private generatePrintHtml(report: Report, includeMetadata: boolean): string {
    const contentHtml = this.markdownToHtml(report.content || '');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${this.escapeHtml(report.name)}</title>
  <style>
    @page {
      size: A4;
      margin: 2cm;
    }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
    * { box-sizing: border-box; }
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.5;
      color: #000;
      margin: 0;
      padding: 20px;
    }
    h1 {
      font-size: 24pt;
      color: #000;
      border-bottom: 2px solid #000;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    h2 {
      font-size: 18pt;
      color: #000;
      margin-top: 25px;
      margin-bottom: 10px;
    }
    h3 {
      font-size: 14pt;
      color: #000;
    }
    .metadata {
      background: #f5f5f5;
      border: 1px solid #ddd;
      padding: 15px;
      margin: 15px 0;
      page-break-inside: avoid;
    }
    .metadata table {
      width: 100%;
      border-collapse: collapse;
    }
    .metadata td {
      padding: 5px 10px;
      border-bottom: 1px solid #eee;
    }
    .metadata td:first-child {
      font-weight: bold;
      width: 150px;
    }
    .content {
      margin: 20px 0;
    }
    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #ccc;
      font-size: 10pt;
      color: #666;
      text-align: center;
    }
    pre {
      background: #f4f4f4;
      padding: 10px;
      border: 1px solid #ddd;
      overflow-x: auto;
      font-size: 10pt;
    }
    code {
      background: #f4f4f4;
      padding: 2px 4px;
      font-size: 10pt;
    }
    ul, ol {
      padding-left: 25px;
    }
    li {
      margin: 3px 0;
    }
    blockquote {
      border-left: 3px solid #ccc;
      margin: 10px 0;
      padding-left: 15px;
      color: #555;
    }
  </style>
</head>
<body>
  <h1>${this.escapeHtml(report.name)}</h1>

  ${includeMetadata ? this.generateMetadataSection(report) : ''}

  ${report.description ? `
  <h2>Description</h2>
  <p>${this.escapeHtml(report.description)}</p>
  ` : ''}

  <div class="content">
    <h2>Report Content</h2>
    ${contentHtml}
  </div>

  ${includeMetadata && report.tokenUsage ? this.generateTokenUsageSection(report.tokenUsage) : ''}

  <div class="footer">
    <p>Generated by AI Report System | ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>`;
  }

  private generateMetadataSection(report: Report): string {
    return `
  <div class="metadata">
    <h2>Report Information</h2>
    <table>
      <tr><td>Report Type</td><td>${report.type}</td></tr>
      <tr><td>Status</td><td>${report.status}</td></tr>
      <tr><td>Created</td><td>${new Date(report.createdAt).toLocaleString()}</td></tr>
      ${report.completedAt ? `<tr><td>Completed</td><td>${new Date(report.completedAt).toLocaleString()}</td></tr>` : ''}
      ${report.llmProvider ? `<tr><td>AI Provider</td><td>${report.llmProvider}</td></tr>` : ''}
      ${report.llmModel ? `<tr><td>Model</td><td>${report.llmModel}</td></tr>` : ''}
    </table>
  </div>`;
  }

  private generateTokenUsageSection(tokenUsage: Record<string, any>): string {
    const rows = Object.entries(tokenUsage)
      .map(([key, value]) => `<tr><td>${this.formatKey(key)}</td><td>${value}</td></tr>`)
      .join('');

    return `
  <div class="metadata">
    <h2>Token Usage Statistics</h2>
    <table>${rows}</table>
  </div>`;
  }

  private formatKey(key: string): string {
    return key
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (c) => c.toUpperCase());
  }

  private markdownToHtml(markdown: string): string {
    if (!markdown) return '<p><em>No content generated</em></p>';

    let html = this.escapeHtml(markdown);

    // Headers
    html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');
    html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
    html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');

    // Bold and italic
    html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    // Code blocks
    html = html.replace(/```([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
    html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

    // Lists
    html = html.replace(/^\- (.*$)/gm, '<li>$1</li>');
    html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');

    // Blockquotes
    html = html.replace(/^> (.*$)/gm, '<blockquote>$1</blockquote>');

    // Horizontal rules
    html = html.replace(/^---$/gm, '<hr>');

    // Paragraphs
    html = html.replace(/\n\n/g, '</p><p>');
    html = '<p>' + html + '</p>';

    // Clean up
    html = html.replace(/<p><\/p>/g, '');
    html = html.replace(/<p>(<h[1-6]>)/g, '$1');
    html = html.replace(/(<\/h[1-6]>)<\/p>/g, '$1');
    html = html.replace(/<p>(<ul>)/g, '$1');
    html = html.replace(/(<\/ul>)<\/p>/g, '$1');
    html = html.replace(/<p>(<hr>)<\/p>/g, '$1');
    html = html.replace(/<p>(<pre>)/g, '$1');
    html = html.replace(/(<\/pre>)<\/p>/g, '$1');

    return html;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50);
  }
}
