@startuml act_add_project_member
skinparam defaultFontSize 13
skinparam activityFontSize 12
skinparam activityDiamondFontSize 11
skinparam activityArrowFontSize 10
skinparam partitionFontSize 13

|Người dùng|
start
:Nhấn nút Invite;

|Giao diện|
:Hiển thị form;

|Người dùng|
:Nhập thông tin & Add;

|Giao diện|
:Gửi request;

|Hệ thống|
:Validate dữ liệu;

if (Hợp lệ?) then (không)
  |Giao diện|
  :Báo lỗi;
  stop
endif

|Hệ thống|
:Thêm member;

|Giao diện|
:Thông báo OK;

|Người dùng|
stop
@enduml
