@startuml act_websocket_broadcast
skinparam defaultFontSize 13
skinparam activityFontSize 12
skinparam activityDiamondFontSize 11
skinparam activityArrowFontSize 10
skinparam partitionFontSize 13

|Người dùng|
start
:Thực hiện update;

|Giao diện|
:Gửi HTTP request;

|Hệ thống|
:Thực hiện update;
:Tạo activity log;
:Tạo WebSocket event;
:Broadcast đến members;

|Giao diện|
fork
  :User A nhận confirm;
fork again
  :User B nhận event;
fork again
  :User C nhận event;
end fork
:Update UI real-time;

|Người dùng|
:Thấy thay đổi real-time;
stop
@enduml
