@startuml act_change_project_role
skinparam defaultFontSize 13
skinparam activityFontSize 12
skinparam activityDiamondFontSize 11
skinparam activityArrowFontSize 10
skinparam partitionFontSize 13

|Người dùng|
start
:Chọn member & Change Role;

|Giao diện|
:Dialog & chọn role;

|Hệ thống|
:Validate quyền;

if (Hợp lệ?) then (không)
  |Giao diện|
  :Báo lỗi;
  stop
endif

|Hệ thống|
:Cập nhật & log;

|Giao diện|
:Thông báo thành công;

|Người dùng|
stop
@enduml
