@startuml
!theme plain
skinparam defaultFontSize 11
skinparam usecaseFontSize 10

left to right direction

actor "Project Lead" as PL

usecase "Tạo sprint mới" as UC_Create
usecase "Kiểm tra\nthông tin" as UC_Validate
usecase "Set trạng thái\nFUTURE" as UC_SetStatus
usecase "Tạo sprint\ncontainer" as UC_Container

PL --> UC_Create

UC_Validate .up.> UC_Create : <<include>>
UC_SetStatus .up.> UC_Create : <<include>>
UC_Container .up.> UC_Create : <<include>>



@enduml
