@startuml
!theme plain
skinparam defaultFontSize 11
skinparam usecaseFontSize 10

left to right direction

actor "Project Lead" as PL

usecase "Bắt đầu sprint" as UC_Start
usecase "Kiểm tra\ntrạng thái" as UC_ValidateStatus
usecase "Kiểm tra\nACTIVE sprint" as UC_CheckActive
usecase "Chuyển status\nFUTURE→ACTIVE" as UC_ChangeStatus
usecase "Tạo snapshot\nban đầu" as UC_Snapshot

PL --> UC_Start

UC_ValidateStatus .up.> UC_Start : <<include>>
UC_CheckActive .up.> UC_Start : <<include>>
UC_ChangeStatus .up.> UC_Start : <<include>>
UC_Snapshot .up.> UC_Start : <<include>>




@enduml
