import { Metadata } from "next";

//styles
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="context-menu-portal" />
        <div id="editor-portal" />
        {/* <AppProvider> */}
        <div className="h-screen w-full overflow-hidden bg-custom-background-100 relative flex flex-col">
          <main className="w-full h-full overflow-hidden relative">{children}</main>
        </div>
        {/* </AppProvider> */}
      </body>
    </html>
  );
}
